name = "FractalDim"
uuid = "2faf9402-fea8-4e17-880c-014013ed1f8f"
authors = ["Håkon Pedersen <hakon.pedersen@ntnu.no> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
